spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
  datasource:
    url: ${DATABASE_URL}
    username: ${PROD_DB_USERNAME}
    password : ${PROD_DB_PASSWORD}
    name: bdj-ticket-portal
  jackson:
    serialization:
      write-dates-as-timestamps: false
  sql:
    init:
      mode: always
